const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
async function render(flights){const panel={innerHTML:''};const scope={window:{},document:{querySelector:()=>panel,querySelectorAll:()=>[],addEventListener(){}},setInterval(){},fetch:async()=>({ok:true,json:async()=>({checkedAt:new Date().toISOString(),flights})}),AbortSignal,Intl,Date};vm.createContext(scope);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/flights.js'),'utf8'),scope);await scope.window.TripFlights.refresh();return panel.innerHTML;}
const tracker=()=>({available:true,state:'matched',observedAt:new Date().toISOString(),scheduledDeparture:'2026-10-07T07:35:00Z',scheduledArrival:'2026-10-07T10:35:00Z',estimatedActualDeparture:'2026-10-07T07:50:00Z',actualDeparture:false,departureGate:'A12',status:'Scheduled'});
test('return converts Istanbul departure and Zurich arrival independently',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-07',available:false,tracker:tracker()}]);assert(html.includes('>10:50</strong>'));assert(html.includes('>12:35</strong>'));assert(html.includes('Gate IST'));assert(html.includes('A12'));assert(!html.includes('>09:50</strong>'));assert(html.includes('FlightStats'));});
test('official Zurich information wins on the Zurich side',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-07',available:true,state:'matched',observedAt:new Date().toISOString(),scheduledArrival:'2026-10-07T10:35:00Z',estimatedArrival:'2026-10-07T10:55:00Z',tracker:tracker()}]);assert(html.includes('>12:55</strong>'));assert(html.includes('>10:50</strong>'));assert(html.includes('Flughafen Zürich'));});
test('same flight number from another day is never presented as this trip',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-06',available:false,tracker:tracker()}]);assert(html.includes('>10:35</strong>'));assert(!html.includes('>10:50</strong>'));assert(!html.includes('A12'));});
test('retained tracker data is visibly stale',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-07',available:false,tracker:{...tracker(),state:'retained'}}]);assert(html.includes('Letzter bekannter Stand'));});
test('fresh tracker replaces stale airport gates and status',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-07',available:true,state:'retained',observedAt:'2026-09-20T08:00:00Z',scheduledArrival:'2026-10-07T10:35:00Z',gate:'OLD',statusText:'Alter Status',tracker:{...tracker(),arrivalGate:'NEW'}}]);assert(html.includes('NEW'));assert(!html.includes('OLD'));assert(!html.includes('Alter Status'));});
test('source outage is distinguished from unpublished flight date',async()=>{const html=await render([{id:'return',number:'TK1207',date:'2026-10-07',available:false,state:'unreachable',tracker:{available:false,state:'not-published'}}]);assert(html.includes('Datenquelle gerade nicht erreichbar'));assert(html.includes('>10:35</strong>'));});
