const {test}=require('node:test'),assert=require('node:assert/strict'),shared=require('../dist/shared-state.js');
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
function server(){let state=shared.initial(['ep0']),online=true;const seen=new Set();return {get state(){return state},set online(v){online=v},fetch:async(url,request)=>{
  if(!online)throw Error('network');const args=JSON.parse(request.body),method=url.split('/').pop();let result;
  if(method==='istanbul_login')result=args.p_code==='test-code'?{ok:true,token:'valid-session',state}:{ok:false,error:'auth'};
  else if(args.p_token!=='valid-session')result={ok:false,error:'auth'};
  else if(method==='istanbul_state')result={ok:true,state};
  else try{if(!seen.has(args.p_operation.operationId)){state=shared.reduce(state,args.p_operation);seen.add(args.p_operation.operationId);}result={ok:true,state};}catch(e){result={ok:false,error:e.message};}
  const body=JSON.parse(JSON.stringify(result));return {ok:true,json:async()=>body};
}};}
let id=0;const device=(backend,storage=memory(),configured=true)=>shared.create({config:configured?{url:'https://example.test',key:'public-test-key'}:{url:'',key:''},defaults:['ep0'],allowed:['ep0','ep11','ep56','ep12'],booked:['ep12'],storage,fetcher:backend.fetch,uuid:()=>`00000000-0000-0000-0000-${String(++id).padStart(12,'0')}`});
test('two devices merge different favourites and share unchecking',async()=>{const api=server(),a=device(api),b=device(api);await a.login('test-code');await b.login('test-code');await Promise.all([a.favorite('ep11',true),b.favorite('ep56',true)]);await a.refresh();await b.refresh();assert.deepEqual(new Set(a.get().state.favorites),new Set(['ep0','ep11','ep56']));assert.deepEqual(a.get().state.favorites,b.get().state.favorites);await b.favorite('ep11',false);await a.refresh();assert(!a.get().state.favorites.includes('ep11'));});
test('apply and undo are shared while favourite checks remain intact',async()=>{const api=server(),a=device(api),b=device(api);await a.login('test-code');await b.login('test-code');await a.favorite('ep11',true);await a.apply(a.get().state.revision);await b.refresh();assert.equal(b.get().state.activePlan.version,1);assert.equal(b.get().state.history.length,1);await b.undo(b.get().state.planRevision);await a.refresh();assert.equal(a.get().state.activePlan,null);assert(a.get().state.favorites.includes('ep11'));});
test('stale preview cannot replace another devices newer selection',async()=>{const api=server(),a=device(api),b=device(api);await a.login('test-code');await b.login('test-code');const preview=a.get().state.revision;await b.favorite('ep56',true);await assert.rejects(a.apply(preview),/conflict/);assert.equal(api.state.activePlan,null);});
test('offline checkboxes queue visibly and replay once after reconnect',async()=>{const api=server(),a=device(api);await a.login('test-code');api.online=false;await a.favorite('ep11',true);assert.equal(a.get().pending,1);assert.equal(a.get().phase,'offline');assert(a.get().state.favorites.includes('ep11'));assert(!api.state.favorites.includes('ep11'));api.online=true;await a.refresh();assert.equal(a.get().pending,0);assert.equal(api.state.favorites.filter(x=>x==='ep11').length,1);});
test('booked points cannot be favoured and incorrect codes do not unlock',async()=>{const api=server(),a=device(api);await assert.rejects(a.login('wrong'),/auth/);assert.equal(a.get().authenticated,false);await assert.rejects(a.favorite('ep11',true),/auth/);await a.login('test-code');await a.favorite('ep12',true);assert(!api.state.favorites.includes('ep12'));});
test('unconfigured mode explicitly stays local and supports persistent undo',async()=>{const api=server(),storage=memory(),a=device(api,storage,false);await a.favorite('ep11',true);await a.apply(a.get().state.revision);const b=device(api,storage,false);assert.equal(b.get().phase,'local');assert.equal(b.get().configured,false);assert.equal(b.get().state.history.length,1);await b.undo(b.get().state.planRevision);assert.equal(b.get().state.activePlan,null);assert(b.get().state.favorites.includes('ep11'));});
test('undo rejects a stale history revision',async()=>{const state=shared.reduce(shared.initial(['ep0']),{kind:'apply',expectedRevision:0});assert.throws(()=>shared.reduce(state,{kind:'undo',expectedPlanRevision:0}),/conflict/);});
